######################################################################
# Automatically generated by qmake (3.1) Sat Dec 10 19:09:38 2022
######################################################################

TEMPLATE = app
TARGET = hello - world
INCLUDEPATH += .
QT += widgets

#Input
SOURCES+= main . cpp
